name: Art PR Comment
run-name: Art PR Comment
on: 
    pull_request_target: 
        types: [opened]
        paths: 'art/**'
jobs:
  comment-pr:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.log(context.payload)
            const pr = context.payload.pull_request;
            const owner = context.payload.repository.owner;
            const repo = context.payload.repository.repo;
            const number = context.payload.number;
            const changedFiles = await github.rest.pulls.listFiles({
                owner,
                repo,
                number
            });
            console.log(changedFiles)
            
            let commentbody = "";
            let also = false;

            for (const file of changedFiles) {
              if (!file.filename.endsWith(index.js)) continue;
              const rawUrl = `https://raw.githubusercontent.com/${context.repository.owner}/${context.repository.repo}/${context.sha}/${file.filename}`;
              const blotUrl = `https://blot.hackclub.com/editor?src=${rawUrl}`;

              if (!also) {
                commentbody += `\`${file.path}\` looks like art! [preview it in the editor](${blotUrl})\n`
                also = true
              } else {
                commentbody += `\`${file.path}\` *also* looks like art! [preview it in the editor](${blotUrl})\n`
              }
            }

            if (!also) return;

            github.rest.issues.createComment({
              issue_number: pullRequest.number,
              owner: pullRequest.repository.owner,
              repo: pullRequest.repository.repo,
              body: commentBody
            });

      
